services:
  api:
    image: ejemplo-api:v1.0.0
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://@db:27017 
      # - MONGO_URI=mongodb://127.0.0.1:27017
      # - MONGO_URI=mongodb://usuario:contraseña@db:27017 #@db hace referencia a la ip del contendedor db
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=usuario
      - MONGO_INITDB_ROOT_PASSWORD=contraseña
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: